version: '3'

services:
  web:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      NODE_ENV: development
  # db:
  #   image: mysql:8.0.28-alpine
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: myuser
  #     MYSQL_PASSWORD: mypassword
  #   ports:
  #     - "3306:3306"

volumes:
  mongo-data:
